# Example configuration settings for the multi-language project
app_name: "Chat Application"
version: "1.0.0"
logging:
  level: "info"
  file: "logs/app.log"
database:
  host: "localhost"
  port: 5432
  username: "user"
  password: "password"
  db_name: "chat_app_db"
server:
  host: "0.0.0.0"
  port: 8080
features:
  enable_chat: true
  enable_notifications: true
  enable_logging: true
